### ISSUE TITLE
Issues with Carbon Black Pluginv1.0.4

### ISSUE THREAD

**Issue by SivaMulpuru** [netskopeoss/ta_cloud_exchange#20]
1. Plugin Setup UI conflicts with recommended value and data check ![image](https://user-images.githubusercontent.com/48166562/191641002-555bbced-98ce-4840-9103-f7a98ea82872.png)

2. Fails to complete the setup, even with correct data [verified with postman]
![image](https://user-images.githubusercontent.com/48166562/191641431-86aeb4d9-fcce-489b-815c-cdfab6040956.png)

**Comment by drwillis07** [comment]
Siva - can you please open a ticket with support@netskope.com and we'll see what we can do to help you out. This looks like an issue with the API token credentials. 

You need to set Create, Read, and Update for the following restful endpoints:
Custom Detections > Org.watchlist
Custom Detections > Org.feeds

FYI The Override reputation does nothing except enable you to create a reputation for a given plugin if one is not present in the raw feed (not sure if your mouse was there to tell us you suspected that or not).

**Comment by SivaMulpuru** [comment]
Hi @drwillis07, it turned out to be API access issue. Choose Org.alerts.notes instead of Org.alerts. 

Regarding "Override reputation", the tip says to use 0 for default but the webapp complains 0 is not valid value and only accepts 1-10.
